# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: env_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x65nv_server.proto\x12\x0b\x65val_server"\x1a\n\nEnvRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\x1b\n\x08\x45nvReply\x12\x0f\n\x07message\x18\x01 \x01(\t"\x19\n\x06\x45nvObs\x12\x0f\n\x07message\x18\x01 \x01(\t2\xfd\x01\n\tEnvServer\x12\x38\n\x06GetObs\x12\x17.eval_server.EnvRequest\x1a\x13.eval_server.EnvObs"\x00\x12\x38\n\x04Step\x12\x17.eval_server.EnvRequest\x1a\x15.eval_server.EnvReply"\x00\x12?\n\x0bRegisterEnv\x12\x17.eval_server.EnvRequest\x1a\x15.eval_server.EnvReply"\x00\x12;\n\x07\x43onnect\x12\x17.eval_server.EnvRequest\x1a\x15.eval_server.EnvReply"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "env_server_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _ENVREQUEST._serialized_start = 33
    _ENVREQUEST._serialized_end = 59
    _ENVREPLY._serialized_start = 61
    _ENVREPLY._serialized_end = 88
    _ENVOBS._serialized_start = 90
    _ENVOBS._serialized_end = 115
    _ENVSERVER._serialized_start = 118
    _ENVSERVER._serialized_end = 371
# @@protoc_insertion_point(module_scope)
