# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: env_server.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65nv_server.proto\x12\x0b\x65val_server\"*\n\x0c\x41gentActions\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"c\n\nVecEnvDesc\x12\x0e\n\x06\x65nv_id\x18\x01 \x01(\t\x12\x0f\n\x07\x65nv_num\x18\x02 \x01(\x05\x12\x1e\n\x11max_episode_steps\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x14\n\x12_max_episode_steps\"5\n\x0cObservations\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x13\n\x0bobservation\x18\x02 \x01(\t\"\x8d\x01\n\nEnvRequest\x12\x14\n\x0cinstance_ids\x18\x01 \x03(\t\x12\x16\n\tb_actions\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x32\n\x0cvec_env_desc\x18\x03 \x01(\x0b\x32\x17.eval_server.VecEnvDescH\x01\x88\x01\x01\x42\x0c\n\n_b_actionsB\x0f\n\r_vec_env_desc\"\x86\x01\n\x08\x45nvReply\x12\x15\n\x08\x62_states\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x1b\n\x0e\x62_observations\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x14\n\x0cinstance_ids\x18\x03 \x03(\t\x12\x10\n\x08\x61ll_done\x18\x04 \x01(\x08\x42\x0b\n\t_b_statesB\x11\n\x0f_b_observations2\x91\x02\n\tEnvServer\x12\x42\n\x0eGetStateAndObs\x12\x17.eval_server.EnvRequest\x1a\x15.eval_server.EnvReply\"\x00\x12\x38\n\x04Step\x12\x17.eval_server.EnvRequest\x1a\x15.eval_server.EnvReply\"\x00\x12?\n\x0bRegisterEnv\x12\x17.eval_server.EnvRequest\x1a\x15.eval_server.EnvReply\"\x00\x12\x45\n\x11RequestEvaluation\x12\x17.eval_server.EnvRequest\x1a\x15.eval_server.EnvReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'env_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTACTIONS']._serialized_start=33
  _globals['_AGENTACTIONS']._serialized_end=75
  _globals['_VECENVDESC']._serialized_start=77
  _globals['_VECENVDESC']._serialized_end=176
  _globals['_OBSERVATIONS']._serialized_start=178
  _globals['_OBSERVATIONS']._serialized_end=231
  _globals['_ENVREQUEST']._serialized_start=234
  _globals['_ENVREQUEST']._serialized_end=375
  _globals['_ENVREPLY']._serialized_start=378
  _globals['_ENVREPLY']._serialized_end=512
  _globals['_ENVSERVER']._serialized_start=515
  _globals['_ENVSERVER']._serialized_end=788
# @@protoc_insertion_point(module_scope)
